# Generated by Django 4.0.5 on 2023-03-16 04:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'brand',
            },
        ),
        migrations.CreateModel(
            name='CarEngineandTransmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enginetype', models.CharField(max_length=50)),
                ('enginedisplacement', models.IntegerField(max_length=50)),
                ('noofcylinder', models.IntegerField(max_length=50)),
                ('maxpower', models.IntegerField(max_length=50)),
                ('torque', models.IntegerField(max_length=50)),
                ('transmissiontype', models.CharField(max_length=100)),
                ('drivetype', models.CharField(max_length=50)),
                ('cluchtype', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'CarEngine and Transmission',
            },
        ),
        migrations.CreateModel(
            name='Cartype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'car type',
            },
        ),
        migrations.CreateModel(
            name='Carvarient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'car Varient',
            },
        ),
        migrations.CreateModel(
            name='Comfort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vanitymirror', models.BooleanField(default=True)),
                ('realseatheadrest', models.BooleanField(default=True)),
                ('adjustableheadrest', models.BooleanField(default=True)),
                ('rearseatcentrearmrest', models.BooleanField(default=True)),
                ('heightadjustablefrontseatbelts', models.BooleanField(default=True)),
                ('rearACVents', models.BooleanField(default=True)),
                ('seatLumbarSupport', models.BooleanField(default=True)),
                ('multifunctionSteeringWheel', models.BooleanField(default=True)),
                ('cruiseControl', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'comfort',
            },
        ),
        migrations.CreateModel(
            name='Exterior',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wheel', models.IntegerField(max_length=100)),
                ('colors', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'exterior',
            },
        ),
        migrations.CreateModel(
            name='Fuel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fueltype', models.CharField(max_length=100)),
                ('tankcapicity', models.IntegerField(max_length=50)),
                ('topspeed', models.IntegerField(max_length=50)),
                ('mileage', models.IntegerField(max_length=50)),
            ],
            options={
                'db_table': 'Fuel',
            },
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.IntegerField(max_length=50)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car.brand')),
                ('cartype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car.cartype')),
                ('carvarient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car.carvarient')),
                ('comfort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car.comfort')),
                ('exterior', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car.exterior')),
                ('fuel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car.fuel')),
            ],
            options={
                'db_table': 'car',
            },
        ),
    ]
