# Generated by Django 4.0.5 on 2023-03-16 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='price',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='carengineandtransmission',
            name='enginedisplacement',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='carengineandtransmission',
            name='maxpower',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='carengineandtransmission',
            name='noofcylinder',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='carengineandtransmission',
            name='torque',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='exterior',
            name='wheel',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='fuel',
            name='mileage',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='fuel',
            name='tankcapicity',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='fuel',
            name='topspeed',
            field=models.IntegerField(null=True),
        ),
    ]
